keys:
  - &users:
    - &kassie age14rvrnvfzq4akgmg68r5tglkvk98phzw76wr05hh0dalxnl645dpswchcjl 
  - &hosts:
    - &muhly <age_key>
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *kassie
      - *muhly
